---
name: "Workflow call: Render Readme"

on:
  workflow_call:
    secrets:
      BJWS_APP_ID:
        description: "The ID of the GitHub App"
        required: true
      BJWS_APP_PRIVATE_KEY:
        description: "The private key of the GitHub App"
        required: true

jobs:
  render-readme:
    name: Render README
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2
        id: generate-token
        with:
          app_id: "${{ secrets.BJWS_APP_ID }}"
          private_key: "${{ secrets.BJWS_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Setup Python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4
        with:
          python-version: "3.11"
          cache: "pip" # caching pip dependencies

      - name: Install Python Requirements
        run: |
          pip install -r ./.ci/scripts/requirements.txt && pip freeze

      - name: Render README
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          python ./.ci/scripts/render-readme.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d # v5
        id: auto-commit
        with:
          file_pattern: "README.md"
          commit_message: Render README.md
          commit_user_name: "bjw-s-bot[bot]"
          commit_user_email: 87358111+bjw-s-bot[bot]@users.noreply.github.com
          commit_author: bjw-s-bot[bot] <87358111+bjw-s-bot[bot]@users.noreply.github.com>
